namespace Ndapi.Enums
{
    public enum ObjectType
    {
        Any = NdapiConstants.D2FFO_ANY,
        Alert = NdapiConstants.D2FFO_ALERT,
        AttachedLibrary = NdapiConstants.D2FFO_ATT_LIB,
        Block = NdapiConstants.D2FFO_BLOCK,
        Canvas = NdapiConstants.D2FFO_CANVAS,
        ColumnValue = NdapiConstants.D2FFO_COLUMN_VALUE,
        CompoundText = NdapiConstants.D2FFO_CMPTXT,
        Coordinate = NdapiConstants.D2FFO_COORD,
        DataSourceArgument = NdapiConstants.D2FFO_DAT_SRC_ARG,
        DataSourceColumn = NdapiConstants.D2FFO_DAT_SRC_COL,
        Editor = NdapiConstants.D2FFO_EDITOR,
        Font = NdapiConstants.D2FFO_FONT,
        FormModule = NdapiConstants.D2FFO_FORM_MODULE,
        FormParameter = NdapiConstants.D2FFO_FORM_PARAM,
        Graphic = NdapiConstants.D2FFO_GRAPHIC,
        Item = NdapiConstants.D2FFO_ITEM,
        LibraryProgramUnit = NdapiConstants.D2FFO_LIB_PROG_UNIT,
        LibraryModule = NdapiConstants.D2FFO_LIBRARY_MODULE,
        LOV = NdapiConstants.D2FFO_LOV,
        ColumnMapping = NdapiConstants.D2FFO_LV_COLMAP,
        Menu = NdapiConstants.D2FFO_MENU,
        MenuItem = NdapiConstants.D2FFO_MENU_ITEM,
        MenuModule = NdapiConstants.D2FFO_MENU_MODULE,
        MenuParameter = NdapiConstants.D2FFO_MENU_PARAM,
        ObjectGroup = NdapiConstants.D2FFO_OBJ_GROUP,
        ObjectGroupChild = NdapiConstants.D2FFO_OBG_CHILD,
        ObjectLibrary = NdapiConstants.D2FFO_OBJ_LIB,
        ObjectLibraryTab = NdapiConstants.D2FFO_OBJ_LIB_TAB,
        Point = NdapiConstants.D2FFO_POINT,
        ProgramUnit = NdapiConstants.D2FFO_PROG_UNIT,
        PropertyClass = NdapiConstants.D2FFO_PROP_CLASS,
        RadioButton = NdapiConstants.D2FFO_RADIO_BUTTON,
        RecordGroup = NdapiConstants.D2FFO_REC_GROUP,
        BlockRelation = NdapiConstants.D2FFO_RELATION,
        Report = NdapiConstants.D2FFO_REPORT,
        ColumnSpecification = NdapiConstants.D2FFO_RG_COLSPEC,
        TabPage = NdapiConstants.D2FFO_TAB_PAGE,
        TextSegment = NdapiConstants.D2FFO_TEXT_SEG,
        Trigger = NdapiConstants.D2FFO_TRIGGER,
        TriggerStep = NdapiConstants.D2FFO_TRIG_STEP,
        VisualAttribute = NdapiConstants.D2FFO_VIS_ATTR,
        Window = NdapiConstants.D2FFO_WINDOW,
        Undefined = NdapiConstants.D2FFO_UNDEFINED
}
}
