name: Build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build dll for Forms 6.0.8
        run: dotnet build -c Release_6_0_8

      - name: Set version
        run: |
          echo "Buid version is ${{github.run_number}}"
          sed -i "s/\(<Version>\([0-9]\+\.\)\{2\}\)\([0-9]\+\)/\1${{github.run_number}}/" Ndapi/Ndapi.csproj

      - name: Build dll for Forms 12.2.1.3
        run: dotnet build -c Release_12_2_1_3 -p:Platform=x64

      - name: Build NuGet package
        run: dotnet pack -c Release --no-build

      - name: Build trimmed sample with NativeAOT
        run: dotnet publish -c Release_12_2_1_3 -p:"Platform=x64;PublishAot=true" -r linux-x64

      - name: Add NuGet source
        run: dotnet nuget add source --username felipebz --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/felipebz/index.json"

      - name: Publish to GitHub Packages
        run: dotnet nuget push "Ndapi/**.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source github
